(() => {
  const BUILD = "v73";
  const SOURCE = "castles-v62";
  const SYMBOL = "castles-v62-symbol";
  const LABELS = "castles-v62-labels";
  const ZONE_SOURCE = "castle-checkin-zone-v62";
  const ZONE_FILL = "castle-checkin-zone-v62-fill";
  const ZONE_LINE = "castle-checkin-zone-v62-line";
  const LOCATION_MAX_AGE_MS = 2 * 60 * 1000;
  const DEFAULT_ACCURACY_M = 500;

  let installed = false;
  let controllerActive = false;
  let zoneData = null;
  let zonesById = new Map();
  let selectedCastleId = null;
  let position = null;
  let mapBound = false;
  let mapLinksObserver = null;

  const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
  function getMap(){try{return typeof map!=="undefined"?map:null;}catch{return null;}}
  function castles(){return Array.isArray(window.OnsenCastleDomain?.data?.entities)?window.OnsenCastleDomain.data.entities:[];}
  function castleById(id){return castles().find((x)=>String(x.id)===String(id))||null;}
  function zoneFor(id){return zonesById.get(String(id||""))||null;}
  function esc(value){return String(value??"").replace(/[&<>'\"]/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
  function formatDistance(m){const n=Number(m);if(!Number.isFinite(n))return "—";return n<1000?`${Math.round(n)}m`:`${(n/1000).toFixed(n<10000?1:0)}km`;}
  function haversineM(lat1,lng1,lat2,lng2){const R=6371000,rad=(v)=>v*Math.PI/180,dLat=rad(lat2-lat1),dLng=rad(lng2-lng1),a=Math.sin(dLat/2)**2+Math.cos(rad(lat1))*Math.cos(rad(lat2))*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
  function circlePolygon(lat,lng,radiusM,steps=64){const R=6371000,latRad=lat*Math.PI/180,latDelta=radiusM/R,lngDelta=radiusM/(R*Math.max(.15,Math.cos(latRad))),coords=[];for(let i=0;i<=steps;i++){const a=i/steps*Math.PI*2;coords.push([lng+lngDelta*Math.cos(a)*180/Math.PI,lat+latDelta*Math.sin(a)*180/Math.PI]);}return {type:"Polygon",coordinates:[coords]};}

  function loadZones(){
    const data=window.OnsenCastleDomain?.data?.zoneData;
    if(!Array.isArray(data?.entries)||data.entries.length!==200)throw new Error(`castle zone count must be 200; got ${data?.entries?.length??0}`);
    zoneData=data;
    zonesById=new Map(data.entries.map((entry)=>[String(entry.castleId),{...entry,radiusM:Math.max(500,Number(entry.radiusM)||750),accuracyRequiredM:Math.max(DEFAULT_ACCURACY_M,Number(entry.accuracyRequiredM)||DEFAULT_ACCURACY_M)}]));
    return data;
  }

  function createIcon(fill,border,flag){const size=96,c=document.createElement("canvas");c.width=size;c.height=size;const x=c.getContext("2d");x.clearRect(0,0,size,size);x.beginPath();x.arc(48,48,38,0,Math.PI*2);x.fillStyle=fill;x.fill();x.lineWidth=7;x.strokeStyle=border;x.stroke();x.fillStyle="#fff8e9";x.fillRect(29,49,38,21);x.fillRect(34,40,28,12);x.fillRect(40,31,16,12);x.beginPath();x.moveTo(36,40);x.lineTo(48,27);x.lineTo(60,40);x.closePath();x.fill();x.fillStyle=border;x.fillRect(44,56,8,14);x.fillRect(34,53,6,6);x.fillRect(56,53,6,6);if(flag){x.strokeStyle="#fff8e9";x.lineWidth=4;x.beginPath();x.moveTo(63,26);x.lineTo(63,45);x.stroke();x.fillStyle="#fff8e9";x.beginPath();x.moveTo(64,27);x.lineTo(78,32);x.lineTo(64,37);x.closePath();x.fill();}return x.getImageData(0,0,size,size);}
  function ensureIcons(m){const icons={"castle-v62-unvisited":createIcon("#35566f","#20394e",false),"castle-v62-visited":createIcon("#8f6e31","#59451f",false),"castle-v62-strict":createIcon("#467c55","#285334",true)};for(const [id,img] of Object.entries(icons)){try{if(!m.hasImage(id))m.addImage(id,img,{pixelRatio:2});}catch{}}}
  function buildGeoJson(){const visits=window.OnsenCastleVisits;return {type:"FeatureCollection",features:castles().map((castle)=>{const zone=zoneFor(castle.id);if(!zone)return null;return {type:"Feature",properties:{id:castle.id,name:castle.name,prefecture:castle.prefecture,japan100No:Number(castle.japan100No),visited:!!visits?.isVisited?.(castle.id),strict:!!visits?.isStrictGps?.(castle.id)},geometry:{type:"Point",coordinates:[Number(zone.lng),Number(zone.lat)]}};}).filter(Boolean)};}
  function setOwnLayer(id,visible){const m=getMap();if(!m?.getLayer?.(id))return;try{m.setLayoutProperty(id,"visibility",visible?"visible":"none");}catch{}}
  function refreshSource(){getMap()?.getSource(SOURCE)?.setData?.(buildGeoJson());}
  function clearZone(){getMap()?.getSource(ZONE_SOURCE)?.setData?.({type:"FeatureCollection",features:[]});}
  function renderZone(id){const m=getMap(),source=m?.getSource(ZONE_SOURCE),zone=zoneFor(id);if(!source||!zone)return false;source.setData({type:"FeatureCollection",features:[{type:"Feature",properties:{castleId:id,radiusM:zone.radiusM},geometry:circlePolygon(Number(zone.lat),Number(zone.lng),Number(zone.radiusM))}]});return true;}

  function ensureLayers(){
    const m=getMap();if(!m||!zoneData||!m.isStyleLoaded?.())return false;ensureIcons(m);
    try{if(!m.getSource(SOURCE))m.addSource(SOURCE,{type:"geojson",data:buildGeoJson()});else refreshSource();}catch{return false;}
    try{if(!m.getLayer(SYMBOL))m.addLayer({id:SYMBOL,type:"symbol",source:SOURCE,layout:{visibility:"none","icon-image":["case",["==",["get","strict"],true],"castle-v62-strict",["==",["get","visited"],true],"castle-v62-visited","castle-v62-unvisited"],"icon-size":["interpolate",["linear"],["zoom"],3.6,.34,8,.5,12,.68],"icon-allow-overlap":true,"icon-ignore-placement":true}});}catch{}
    try{if(!m.getLayer(LABELS))m.addLayer({id:LABELS,type:"symbol",source:SOURCE,minzoom:7.4,layout:{visibility:"none","text-field":["concat","#",["to-string",["get","japan100No"]]," ",["get","name"]],"text-size":["interpolate",["linear"],["zoom"],7.4,10,12,13],"text-offset":[0,1.8],"text-anchor":"top","text-optional":true},paint:{"text-color":"#3f493d","text-halo-color":"#fffaf0","text-halo-width":1.5}});}catch{}
    try{if(!m.getSource(ZONE_SOURCE))m.addSource(ZONE_SOURCE,{type:"geojson",data:{type:"FeatureCollection",features:[]}});}catch{}
    try{if(!m.getLayer(ZONE_FILL))m.addLayer({id:ZONE_FILL,type:"fill",source:ZONE_SOURCE,layout:{visibility:"none"},paint:{"fill-color":"#477d55","fill-opacity":.13}});}catch{}
    try{if(!m.getLayer(ZONE_LINE))m.addLayer({id:ZONE_LINE,type:"line",source:ZONE_SOURCE,layout:{visibility:"none"},paint:{"line-color":"#3f714d","line-width":2,"line-opacity":.85}});}catch{}
    if(selectedCastleId)renderZone(selectedCastleId);else clearZone();
    bindMapInteractions();
    window.dispatchEvent(new CustomEvent("onsen-castle-map-layers-ready",{detail:{build:BUILD}}));
    return true;
  }

  function bindMapInteractions(){const m=getMap();if(!m||mapBound)return;mapBound=true;m.on("click",(event)=>{if(!controllerActive)return;const layers=[SYMBOL,LABELS].filter((id)=>m.getLayer(id));if(!layers.length)return;let features=[];try{features=m.queryRenderedFeatures(event.point,{layers});}catch{}if(!features.length)return;const id=features[0]?.properties?.id;if(id)selectCastle(id,{fly:false});});m.on("mousemove",(event)=>{if(!controllerActive)return;const layers=[SYMBOL,LABELS].filter((id)=>m.getLayer(id));if(!layers.length)return;let hit=[];try{hit=m.queryRenderedFeatures(event.point,{layers});}catch{}m.getCanvas().style.cursor=hit.length?"pointer":"";});m.on("style.load",()=>{setTimeout(()=>{ensureLayers();window.OnsenMapDomainV73?.apply?.();},0);});}

  function ensurePanel(){const main=document.querySelector(".main"),onsenPanel=main?.querySelector(":scope > .panel:not(.castle-map-panel-v62):not(.scenic-map-panel-v71)");if(!main||!onsenPanel)return null;let panel=document.getElementById("castleMapPanelV62");if(panel)return panel;panel=document.createElement("section");panel.id="castleMapPanelV62";panel.className="panel castle-map-panel-v62";panel.hidden=true;panel.innerHTML=`<div class="castle-map-empty-v62" id="castleMapEmptyV62"><span>JAPAN 100 + CONTINUED 100</span><h2>城を選択</h2><p>地図の城ピンをタップしてください。</p></div><div id="castleMapDetailV62" hidden><div class="castle-map-title-v62"><div><span id="castleMapNoV62">#---</span><h2 id="castleMapNameV62">城</h2><p id="castleMapPlaceV62"></p></div><b id="castleMapStatusV62">未訪問</b></div><div class="castle-map-metrics-v62"><div><span>距離</span><b id="castleMapDistanceV62">現在地未取得</b></div><div><span>GPS精度</span><b id="castleMapAccuracyV62">—</b></div><div><span>判定半径</span><b id="castleMapRadiusV62">—</b></div></div><div class="castle-map-actions-v62"><button id="castleMapLocateV62" type="button" class="secondary">現在地を確認</button><button id="castleMapCheckinV62" type="button" disabled>城チェックイン</button></div><div id="castleMapMessageV62" class="castle-map-message-v62">GPSチェックインは過去訪問登録とは別に記録します。</div><details class="details" open><summary>人物との縁</summary><div id="castleMapCharactersV62" class="castle-map-characters-v62"></div></details></div>`;onsenPanel.insertAdjacentElement("afterend",panel);panel.querySelector("#castleMapLocateV62")?.addEventListener("click",()=>resolveCurrentPosition(true));panel.querySelector("#castleMapCheckinV62")?.addEventListener("click",performCheckin);return panel;}
  function candidateMarkup(id){const candidates=window.OnsenCharacterRuntime?.candidatesForCastle?.(id)||[];if(!candidates.length)return `<div class="castle-map-no-character-v62">この城に直接紐づく人物は未設定です。</div>`;return candidates.map((c)=>{const guaranteed=(c.recruitment?.guaranteedCastleIds||[]).includes(id),owned=!!window.OnsenCharacterRuntime?.getStatus?.(c.id)?.recruitedNow;return `<div class="castle-character-chip-v62${guaranteed?" guaranteed":""}${owned?" owned":""}"><strong>${esc(c.name)}</strong><span>${owned?"登用済":guaranteed?"初回GPS加入":"登用候補"}</span></div>`;}).join("");}
  function selectedDistance(){const z=zoneFor(selectedCastleId);return !z||!position?null:haversineM(position.lat,position.lng,Number(z.lat),Number(z.lng));}
  function fresh(){return !!position&&Date.now()-Number(position.sampledAt||0)<=LOCATION_MAX_AGE_MS;}
  function updatePanel(){const panel=ensurePanel(),castle=castleById(selectedCastleId),zone=zoneFor(selectedCastleId),empty=document.getElementById("castleMapEmptyV62"),detail=document.getElementById("castleMapDetailV62");if(!panel||!empty||!detail)return;if(!castle||!zone){empty.hidden=false;detail.hidden=true;return;}empty.hidden=true;detail.hidden=false;const visits=window.OnsenCastleVisits,strict=!!visits?.isStrictGps?.(castle.id),visited=!!visits?.isVisited?.(castle.id),distance=selectedDistance(),accuracy=Number(position?.accuracyM),limit=Number(zone.accuracyRequiredM||DEFAULT_ACCURACY_M),accurate=fresh()&&Number.isFinite(accuracy)&&accuracy<=limit,inRange=Number.isFinite(distance)&&distance<=Number(zone.radiusM);document.getElementById("castleMapNoV62").textContent=`#${String(castle.japan100No).padStart(3,"0")} ${Number(castle.japan100No)>=101?"続100":"100名城"}`;document.getElementById("castleMapNameV62").textContent=castle.name;document.getElementById("castleMapPlaceV62").textContent=`${castle.prefecture||""}${castle.region?` ・ ${castle.region}`:""}${castle.castleType?` ・ ${castle.castleType}`:""}`;const status=document.getElementById("castleMapStatusV62");status.textContent=strict?"GPS確認済":visited?"訪問登録済":"未訪問";status.className=strict?"strict":visited?"visited":"";document.getElementById("castleMapDistanceV62").textContent=distance==null?"現在地未取得":formatDistance(distance);document.getElementById("castleMapAccuracyV62").textContent=fresh()&&Number.isFinite(accuracy)?`${Math.round(accuracy)}m`:"—";document.getElementById("castleMapRadiusV62").textContent=formatDistance(zone.radiusM);document.getElementById("castleMapCharactersV62").innerHTML=candidateMarkup(castle.id);const button=document.getElementById("castleMapCheckinV62"),message=document.getElementById("castleMapMessageV62");button.disabled=strict||!(accurate&&inRange);button.textContent=strict?"GPS確認済":"城チェックイン";if(strict)message.innerHTML="<strong>GPS確認済みです。</strong>";else if(!position)message.textContent="「現在地を確認」でGPSを取得してください。";else if(!fresh())message.textContent="位置情報が古いため再取得してください。";else if(!accurate)message.textContent=`GPS精度が不足しています（現在約${Math.round(accuracy)}m / 許容${limit}m）。`;else if(!inRange)message.textContent=`判定範囲外です。城の判定点まで約${formatDistance(distance)}です。`;else message.innerHTML="<strong>チェックイン可能です。</strong>";}

  function resolveCurrentPosition(center=false){const message=document.getElementById("castleMapMessageV62");if(!navigator.geolocation){if(message)message.textContent="この端末は位置情報取得に対応していません。";return Promise.resolve(null);}if(message)message.textContent="現在地を高精度で確認しています…";return new Promise((resolve)=>navigator.geolocation.getCurrentPosition((p)=>{position={lat:Number(p.coords.latitude),lng:Number(p.coords.longitude),accuracyM:Number(p.coords.accuracy||0),sampledAt:Number(p.timestamp||Date.now())};if(center)getMap()?.flyTo?.({center:[position.lng,position.lat],zoom:Math.max(12,getMap()?.getZoom?.()||12)});updatePanel();resolve(position);},(error)=>{console.warn("castle geolocation failed",error);position=null;updatePanel();resolve(null);},{enableHighAccuracy:true,timeout:12000,maximumAge:3000}));}
  function performCheckin(){const castle=castleById(selectedCastleId),zone=zoneFor(selectedCastleId),distance=selectedDistance();if(!castle||!zone||!position||!fresh()||!Number.isFinite(distance)||distance>zone.radiusM)return;const result=window.OnsenCastleVisits?.registerStrictGpsVisit?.(castle.id,{lat:position.lat,lng:position.lng,accuracyM:position.accuracyM,distanceM:distance,radiusM:zone.radiusM,coordinateSource:zone.coordinateStatus||"castle_zone",coordinateVerification:"v73_domain_adapter",freshFix:true});if(result?.ok){refreshSource();updatePanel();try{navigator.vibrate?.([70,40,120]);}catch{}}}
  function selectCastle(id,options={}){const castle=castleById(id),zone=zoneFor(id);if(!castle||!zone)return false;selectedCastleId=castle.id;renderZone(castle.id);updatePanel();window.OnsenMapDomainV73?.apply?.();if(options.fly!==false)getMap()?.flyTo?.({center:[Number(zone.lng),Number(zone.lat)],zoom:Math.max(11,getMap()?.getZoom?.()||11)});return true;}
  function setControllerActive(active){controllerActive=!!active;if(!controllerActive)getMap()&&(getMap().getCanvas().style.cursor="");if(controllerActive&&selectedCastleId)renderZone(selectedCastleId);return controllerActive;}

  function decorateRows(){const root=document.getElementById("castleListRoot");if(!root)return false;for(const row of root.querySelectorAll(".castle-row")){if(row.querySelector("[data-castle-map-v73]"))continue;const node=row.querySelector("[data-castle-id]"),id=node?.dataset.castleId;if(!id||!zoneFor(id))continue;const actions=row.querySelector(".castle-actions");if(!actions)continue;const b=document.createElement("button");b.type="button";b.className="castle-map-link-v62";b.dataset.castleMapV73=id;b.textContent="地図";actions.insertBefore(b,actions.firstChild);}if(root.dataset.castleMapV73Bound!=="1"){root.dataset.castleMapV73Bound="1";root.addEventListener("click",(event)=>{const b=event.target instanceof Element?event.target.closest("[data-castle-map-v73]"):null;if(!b)return;event.preventDefault();window.OnsenMapDomainV73?.open?.("castle",b.dataset.castleMapV73,{source:"castle-row"});},true);}if(!mapLinksObserver){mapLinksObserver=new MutationObserver(()=>requestAnimationFrame(decorateRows));mapLinksObserver.observe(root,{childList:true,subtree:true});}return true;}

  async function install(){if(installed)return;installed=true;for(let i=0;i<300;i++){if(getMap()&&window.OnsenCastleDomain&&window.OnsenCastleVisits)break;await sleep(30);}loadZones();ensurePanel();ensureLayers();bindMapInteractions();window.addEventListener("onsen-castle-visit-changed",()=>{refreshSource();updatePanel();});window.addEventListener("onsen-character-state-changed",updatePanel);window.addEventListener("onsen-character-runtime-ready",updatePanel);window.addEventListener("onsen-app-tab-changed",(e)=>{if(e.detail?.tab==="collection")setTimeout(decorateRows,60);});window.addEventListener("pageshow",()=>{ensureLayers();refreshSource();updatePanel();});let attempts=0;const timer=setInterval(()=>{decorateRows();attempts++;if(attempts>=30||mapLinksObserver)clearInterval(timer);},300);window.OnsenCastleMap={build:BUILD,ensureLayers,setControllerActive,selectedCastleId:()=>selectedCastleId,selectCastle,resolveCurrentPosition,refresh:()=>{ensureLayers();refreshSource();updatePanel();},zones:()=>zoneData,setMode:(next)=>window.OnsenMapDomainV73?.setMode?.(next),getMode:()=>window.OnsenMapDomainV73?.getMode?.()||"onsen",showCastle:(id)=>window.OnsenMapDomainV73?.open?.("castle",id,{source:"castle-api"})};window.dispatchEvent(new CustomEvent("onsen-castle-map-ready",{detail:{build:BUILD,entries:zoneData.entries.length}}));}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>install().catch((e)=>console.warn("castle map v73 init failed",e)),{once:true});else install().catch((e)=>console.warn("castle map v73 init failed",e));
})();