(() => {
  const BUILD = "v68";
  const MODE_KEY = "mapDomainModeV62";
  const CASTLE_SOURCE = "castles-v62";
  const CASTLE_SYMBOL = "castles-v62-symbol";
  const CASTLE_LABELS = "castles-v62-labels";
  const ZONE_SOURCE = "castle-checkin-zone-v62";
  const ZONE_FILL = "castle-checkin-zone-v62-fill";
  const ZONE_LINE = "castle-checkin-zone-v62-line";
  const LOCATION_MAX_AGE_MS = 2 * 60 * 1000;
  const DEFAULT_ACCURACY_M = 500;

  let mode = sessionStorage.getItem(MODE_KEY) === "castle" ? "castle" : "onsen";
  let zoneData = null;
  let zonesById = new Map();
  let selectedCastleId = null;
  let castlePosition = null;
  let mapLinksObserver = null;
  let installed = false;

  function getMap() { try { return typeof map !== "undefined" ? map : null; } catch { return null; } }
  function castleData() { return Array.isArray(window.OnsenCastleDomain?.data?.entities) ? window.OnsenCastleDomain.data.entities : []; }
  function castleById(id) { return castleData().find((castle) => castle.id === id) || null; }
  function zoneFor(id) { return zonesById.get(String(id || "")) || null; }
  function escapeHtml(value) { return String(value ?? "").replace(/[&<>'\"]/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char])); }
  function formatDistance(meters) { const n = Number(meters); if (!Number.isFinite(n)) return "—"; return n < 1000 ? `${Math.round(n)}m` : `${(n / 1000).toFixed(n < 10000 ? 1 : 0)}km`; }
  function haversineM(lat1, lon1, lat2, lon2) { const R=6371000,toRad=(v)=>v*Math.PI/180,dLat=toRad(lat2-lat1),dLon=toRad(lon2-lon1),a=Math.sin(dLat/2)**2+Math.cos(toRad(lat1))*Math.cos(toRad(lat2))*Math.sin(dLon/2)**2; return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a)); }
  function circlePolygon(lat,lng,radiusM,steps=64) { const R=6371000,latRad=lat*Math.PI/180,latDelta=radiusM/R,lngDelta=radiusM/(R*Math.max(.15,Math.cos(latRad))),coords=[]; for(let i=0;i<=steps;i+=1){const a=i/steps*Math.PI*2;coords.push([lng+lngDelta*Math.cos(a)*180/Math.PI,lat+latDelta*Math.sin(a)*180/Math.PI]);} return {type:"Polygon",coordinates:[coords]}; }

  function loadZonesFromDomain() {
    const data = window.OnsenCastleDomain?.data?.zoneData;
    if (!Array.isArray(data?.entries) || data.entries.length !== 200) throw new Error(`castle zone count must be 200; got ${data?.entries?.length ?? 0}`);
    zoneData = data;
    zonesById = new Map(data.entries.map((entry) => [String(entry.castleId), {
      ...entry,
      radiusM: Math.max(500, Number(entry.radiusM) || 750),
      accuracyRequiredM: Math.max(DEFAULT_ACCURACY_M, Number(entry.accuracyRequiredM) || DEFAULT_ACCURACY_M)
    }]));
    for (const castle of castleData()) {
      const zone = zoneFor(castle.id); if (!zone) continue;
      castle.lat = Number(zone.lat); castle.lng = Number(zone.lng);
      castle.checkinRadiusM = Number(zone.radiusM); castle.accuracyRequiredM = Number(zone.accuracyRequiredM);
      castle.coordinateStatus = zone.coordinateStatus;
    }
    return data;
  }

  function createCastleIcon(fill,border,flag) {
    const size=96,canvas=document.createElement("canvas"); canvas.width=size; canvas.height=size; const ctx=canvas.getContext("2d");
    ctx.clearRect(0,0,size,size); ctx.beginPath(); ctx.arc(48,48,38,0,Math.PI*2); ctx.fillStyle=fill; ctx.fill(); ctx.lineWidth=7; ctx.strokeStyle=border; ctx.stroke();
    ctx.fillStyle="#fff8e9"; ctx.fillRect(29,49,38,21); ctx.fillRect(34,40,28,12); ctx.fillRect(40,31,16,12); ctx.beginPath(); ctx.moveTo(36,40); ctx.lineTo(48,27); ctx.lineTo(60,40); ctx.closePath(); ctx.fill(); ctx.fillStyle=border; ctx.fillRect(44,56,8,14); ctx.fillRect(34,53,6,6); ctx.fillRect(56,53,6,6);
    if(flag){ctx.strokeStyle="#fff8e9";ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(63,26);ctx.lineTo(63,45);ctx.stroke();ctx.fillStyle="#fff8e9";ctx.beginPath();ctx.moveTo(64,27);ctx.lineTo(78,32);ctx.lineTo(64,37);ctx.closePath();ctx.fill();}
    return ctx.getImageData(0,0,size,size);
  }
  function addIcons(targetMap){ if(!targetMap.hasImage("castle-v62-unvisited")) targetMap.addImage("castle-v62-unvisited",createCastleIcon("#35566f","#20394e",false),{pixelRatio:2}); if(!targetMap.hasImage("castle-v62-visited")) targetMap.addImage("castle-v62-visited",createCastleIcon("#8f6e31","#59451f",false),{pixelRatio:2}); if(!targetMap.hasImage("castle-v62-strict")) targetMap.addImage("castle-v62-strict",createCastleIcon("#467c55","#285334",true),{pixelRatio:2}); }

  function buildGeoJson(){ const visits=window.OnsenCastleVisits; return {type:"FeatureCollection",features:castleData().map((castle)=>{const zone=zoneFor(castle.id);if(!zone)return null;return {type:"Feature",properties:{id:castle.id,name:castle.name,prefecture:castle.prefecture,japan100No:Number(castle.japan100No),selectionName:castle.selectionName||"日本100名城",visited:!!visits?.isVisited?.(castle.id),strict:!!visits?.isStrictGps?.(castle.id)},geometry:{type:"Point",coordinates:[Number(zone.lng),Number(zone.lat)]}};}).filter(Boolean)}; }
  function installLayers(){ const targetMap=getMap();if(!targetMap||!zoneData)return false;if(targetMap.getSource(CASTLE_SOURCE)){refreshSource();applyMode();return true;}addIcons(targetMap);targetMap.addSource(CASTLE_SOURCE,{type:"geojson",data:buildGeoJson()});targetMap.addLayer({id:CASTLE_SYMBOL,type:"symbol",source:CASTLE_SOURCE,layout:{visibility:mode==="castle"?"visible":"none","icon-image":["case",["==",["get","strict"],true],"castle-v62-strict",["==",["get","visited"],true],"castle-v62-visited","castle-v62-unvisited"],"icon-size":["interpolate",["linear"],["zoom"],3.6,.34,8,.5,12,.68],"icon-allow-overlap":true,"icon-ignore-placement":true}});targetMap.addLayer({id:CASTLE_LABELS,type:"symbol",source:CASTLE_SOURCE,minzoom:7.4,layout:{visibility:mode==="castle"?"visible":"none","text-field":["concat","#",["to-string",["get","japan100No"]]," ",["get","name"]],"text-size":["interpolate",["linear"],["zoom"],7.4,10,12,13],"text-offset":[0,1.8],"text-anchor":"top","text-optional":true},paint:{"text-color":"#3f493d","text-halo-color":"#fffaf0","text-halo-width":1.5}});targetMap.addSource(ZONE_SOURCE,{type:"geojson",data:{type:"FeatureCollection",features:[]}});targetMap.addLayer({id:ZONE_FILL,type:"fill",source:ZONE_SOURCE,layout:{visibility:mode==="castle"?"visible":"none"},paint:{"fill-color":"#477d55","fill-opacity":.13}});targetMap.addLayer({id:ZONE_LINE,type:"line",source:ZONE_SOURCE,layout:{visibility:mode==="castle"?"visible":"none"},paint:{"line-color":"#3f714d","line-width":2,"line-opacity":.85}});
    const selectFeature=(event)=>{const feature=event.features?.[0];if(feature)selectCastle(feature.properties.id,{fly:false});};targetMap.on("click",CASTLE_SYMBOL,selectFeature);targetMap.on("click",CASTLE_LABELS,selectFeature);for(const id of [CASTLE_SYMBOL,CASTLE_LABELS]){targetMap.on("mouseenter",id,()=>{targetMap.getCanvas().style.cursor="pointer";});targetMap.on("mouseleave",id,()=>{targetMap.getCanvas().style.cursor="";});}applyMode();return true; }
  function refreshSource(){getMap()?.getSource(CASTLE_SOURCE)?.setData?.(buildGeoJson());}
  function setLayerVisibility(id,visible){const targetMap=getMap();if(!targetMap?.getLayer(id))return;try{targetMap.setLayoutProperty(id,"visibility",visible?"visible":"none");}catch{}}
  function clearCastleZone(){getMap()?.getSource(ZONE_SOURCE)?.setData?.({type:"FeatureCollection",features:[]});}
  function renderCastleZone(castleId){const source=getMap()?.getSource(ZONE_SOURCE),zone=zoneFor(castleId);if(!source||!zone)return;source.setData({type:"FeatureCollection",features:[{type:"Feature",properties:{castleId,radiusM:zone.radiusM},geometry:circlePolygon(Number(zone.lat),Number(zone.lng),Number(zone.radiusM))}]});}

  function ensureModeSwitch(){const shell=document.querySelector(".map-shell");if(!shell)return null;let root=document.getElementById("mapDomainSwitchV62");if(root)return root;root=document.createElement("div");root.id="mapDomainSwitchV62";root.className="map-domain-switch-v62";root.setAttribute("aria-label","地図カテゴリ切替");root.innerHTML=`<button type="button" data-map-domain="onsen">♨<span>温泉</span></button><button type="button" data-map-domain="castle">🏯<span>名城200</span></button>`;root.addEventListener("click",(event)=>{const button=event.target instanceof Element?event.target.closest("[data-map-domain]"):null;if(button)setMode(button.dataset.mapDomain||"onsen");});shell.appendChild(root);return root;}
  function ensureCastlePanel(){const main=document.querySelector(".main"),onsenPanel=main?.querySelector(":scope > .panel");if(!main||!onsenPanel)return null;let panel=document.getElementById("castleMapPanelV62");if(panel)return panel;panel=document.createElement("section");panel.id="castleMapPanelV62";panel.className="panel castle-map-panel-v62";panel.hidden=true;panel.innerHTML=`<div class="castle-map-empty-v62" id="castleMapEmptyV62"><span>JAPAN 100 + CONTINUED 100</span><h2>城を選択</h2><p>地図の城ピンをタップしてください。</p></div><div id="castleMapDetailV62" hidden><div class="castle-map-title-v62"><div><span id="castleMapNoV62">#---</span><h2 id="castleMapNameV62">城</h2><p id="castleMapPlaceV62"></p></div><b id="castleMapStatusV62">未訪問</b></div><div class="castle-map-metrics-v62"><div><span>距離</span><b id="castleMapDistanceV62">現在地未取得</b></div><div><span>GPS精度</span><b id="castleMapAccuracyV62">—</b></div><div><span>判定半径</span><b id="castleMapRadiusV62">—</b></div></div><div class="castle-map-actions-v62"><button id="castleMapLocateV62" type="button" class="secondary">現在地を確認</button><button id="castleMapCheckinV62" type="button" disabled>城チェックイン</button></div><div id="castleMapMessageV62" class="castle-map-message-v62">GPSチェックインは、自己申告の過去訪問とは別に記録します。</div><details class="details" open><summary>人物との縁</summary><div id="castleMapCharactersV62" class="castle-map-characters-v62"></div></details><details class="details"><summary>GPS判定について</summary><p class="note">日本100名城・続日本100名城の公開参照情報を初期GPS判定点に使用しています。判定半径は500m未満にせず、山城・広域史跡は1.5〜2.5kmへ広げ、現地での取りこぼし回避を優先します。</p></details></div>`;onsenPanel.insertAdjacentElement("afterend",panel);panel.querySelector("#castleMapLocateV62")?.addEventListener("click",()=>resolveCurrentPosition(true));panel.querySelector("#castleMapCheckinV62")?.addEventListener("click",performCheckin);return panel;}

  function candidateMarkup(castleId){const candidates=window.OnsenCharacterRuntime?.candidatesForCastle?.(castleId)||[];if(!candidates.length)return `<div class="castle-map-no-character-v62">この城に直接紐づく人物は未設定です。GPS訪問自体は記録されます。</div>`;return candidates.map((character)=>{const guaranteed=(character.recruitment?.guaranteedCastleIds||[]).includes(castleId),owned=!!window.OnsenCharacterRuntime?.getStatus?.(character.id)?.recruitedNow;return `<div class="castle-character-chip-v62${guaranteed?" guaranteed":""}${owned?" owned":""}"><strong>${escapeHtml(character.name)}</strong><span>${owned?"登用済":guaranteed?"初回GPS加入":"登用候補"}</span></div>`;}).join("");}
  function statusFor(castleId){const visits=window.OnsenCastleVisits,strict=!!visits?.isStrictGps?.(castleId),visited=!!visits?.isVisited?.(castleId);return {strict,visited,label:strict?"GPS確認済":visited?"訪問登録済":"未訪問"};}
  function selectedDistance(){const zone=zoneFor(selectedCastleId);return !zone||!castlePosition?null:haversineM(castlePosition.lat,castlePosition.lng,Number(zone.lat),Number(zone.lng));}
  function positionFresh(){return !!castlePosition&&Date.now()-Number(castlePosition.sampledAt||0)<=LOCATION_MAX_AGE_MS;}
  function updatePanel(){const panel=ensureCastlePanel(),castle=castleById(selectedCastleId),zone=zoneFor(selectedCastleId),empty=document.getElementById("castleMapEmptyV62"),detail=document.getElementById("castleMapDetailV62");if(!panel||!empty||!detail)return;if(!castle||!zone){empty.hidden=false;detail.hidden=true;return;}empty.hidden=true;detail.hidden=false;const status=statusFor(castle.id),distance=selectedDistance(),accuracy=castlePosition?.accuracyM,fresh=positionFresh(),limit=Number(zone.accuracyRequiredM||DEFAULT_ACCURACY_M),accurate=fresh&&Number.isFinite(Number(accuracy))&&Number(accuracy)<=limit,inRange=Number.isFinite(distance)&&distance<=Number(zone.radiusM);document.getElementById("castleMapNoV62").textContent=`#${String(castle.japan100No).padStart(3,"0")} ${Number(castle.japan100No)>=101?"続100":"100名城"}`;document.getElementById("castleMapNameV62").textContent=castle.name;document.getElementById("castleMapPlaceV62").textContent=`${castle.prefecture} ・ ${castle.region}${castle.castleType?` ・ ${castle.castleType}`:""}`;const statusNode=document.getElementById("castleMapStatusV62");statusNode.textContent=status.label;statusNode.className=status.strict?"strict":status.visited?"visited":"";document.getElementById("castleMapDistanceV62").textContent=distance==null?"現在地未取得":formatDistance(distance);document.getElementById("castleMapAccuracyV62").textContent=fresh&&Number.isFinite(Number(accuracy))?`${Math.round(Number(accuracy))}m`:"—";document.getElementById("castleMapRadiusV62").textContent=formatDistance(Number(zone.radiusM));document.getElementById("castleMapCharactersV62").innerHTML=candidateMarkup(castle.id);const button=document.getElementById("castleMapCheckinV62"),message=document.getElementById("castleMapMessageV62");if(status.strict){button.disabled=true;button.textContent="GPSチェックイン済";message.textContent="この城は厳格GPS訪問済みです。";}else if(!fresh){button.disabled=true;button.textContent="現在地を確認してください";message.textContent="「現在地を確認」で新しいGPS位置を取得してください。";}else if(!accurate){button.disabled=true;button.textContent=`位置精度不足（${Math.round(Number(accuracy||0))}m）`;message.textContent=`GPS精度 ${limit}m以内が必要です。もう一度現在地を確認してください。`;}else if(!inRange){button.disabled=true;const remain=Math.max(0,Number(distance)-Number(zone.radiusM));button.textContent=`範囲外（あと${formatDistance(remain)}）`;message.textContent=`城の判定範囲まであと${formatDistance(remain)}です。`;}else{button.disabled=false;button.textContent="城チェックイン";message.textContent=status.visited?"過去訪問登録済みですが、現地GPS確認を追加できます。":"GPS条件を満たしています。初回現地確認として記録できます。";}}

  async function resolveCurrentPosition(centerMap=false){const message=document.getElementById("castleMapMessageV62");if(!navigator.geolocation){if(message)message.textContent="この端末は位置情報取得に対応していません。";return null;}if(message)message.textContent="現在地を高精度で確認しています…";return new Promise((resolve)=>{navigator.geolocation.getCurrentPosition((position)=>{castlePosition={lat:Number(position.coords.latitude),lng:Number(position.coords.longitude),accuracyM:Math.round(Number(position.coords.accuracy||0)),sampledAt:Date.now()};if(centerMap)getMap()?.flyTo?.({center:[castlePosition.lng,castlePosition.lat],zoom:Math.max(12,getMap()?.getZoom?.()||12)});updatePanel();resolve(castlePosition);},(error)=>{console.warn("castle geolocation failed",error);if(message)message.textContent="現在地を取得できませんでした。位置情報の権限とGPS状態を確認してください。";castlePosition=null;updatePanel();resolve(null);},{enableHighAccuracy:true,timeout:12000,maximumAge:3000});});}
  function performCheckin(){const castle=castleById(selectedCastleId),zone=zoneFor(selectedCastleId);if(!castle||!zone||!castlePosition)return;const distance=selectedDistance(),fresh=positionFresh(),accurate=fresh&&Number(castlePosition.accuracyM)<=Number(zone.accuracyRequiredM||DEFAULT_ACCURACY_M),inRange=Number.isFinite(distance)&&distance<=Number(zone.radiusM);if(!fresh||!accurate||!inRange){updatePanel();return;}const before=window.OnsenCharacterRuntime?.loadState?.()||{},owned=new Set(Object.keys(before.recruited||{})),result=window.OnsenCastleVisits?.registerStrictGpsVisit?.(castle.id,{lat:castlePosition.lat,lng:castlePosition.lng,accuracyM:castlePosition.accuracyM,distanceM:Math.round(distance),radiusM:Number(zone.radiusM),coordinateSource:Number(castle.japan100No)>=101?"data/castles-zoku100-v68.csv":"data/castle-checkin-zones-v62.json",coordinateVerification:zone.coordinateStatus,checkedAt:Date.now()});if(!result?.ok){const message=document.getElementById("castleMapMessageV62");if(message)message.textContent="城チェックインを保存できませんでした。";return;}window.OnsenCharacterRuntime?.claimGuaranteedForCastle?.(castle.id);refreshSource();updatePanel();const after=window.OnsenCharacterRuntime?.loadState?.()||{},gainedId=Object.keys(after.recruited||{}).find((id)=>!owned.has(id)),claimedId=after.guaranteedCastleClaimed?.[castle.id]?.characterId||gainedId,character=claimedId?window.OnsenCharacterRuntime?.get?.(claimedId):null,message=document.getElementById("castleMapMessageV62");if(message)message.innerHTML=character?`<strong>チェックイン成功！</strong> ${escapeHtml(character.name)} が仲間になりました。`:`<strong>チェックイン成功！</strong> GPS訪問を記録しました。`;try{navigator.vibrate?.([70,40,120]);}catch{}}

  function selectCastle(castleId,options={}){const castle=castleById(castleId),zone=zoneFor(castleId);if(!castle||!zone)return false;selectedCastleId=castle.id;renderCastleZone(castle.id);updatePanel();if(options.fly!==false)getMap()?.flyTo?.({center:[Number(zone.lng),Number(zone.lat)],zoom:Math.max(11,getMap()?.getZoom?.()||11)});return true;}
  function setMode(next){mode=next==="castle"?"castle":"onsen";sessionStorage.setItem(MODE_KEY,mode);applyMode();return mode;}
  function applyMode(){const targetMap=getMap(),castleMode=mode==="castle",switcher=ensureModeSwitch(),castlePanel=ensureCastlePanel(),main=document.querySelector(".main"),onsenPanel=main?.querySelector(":scope > .panel:not(.castle-map-panel-v62)");if(switcher)for(const button of switcher.querySelectorAll("[data-map-domain]")){const active=button.dataset.mapDomain===mode;button.classList.toggle("active",active);button.setAttribute("aria-pressed",active?"true":"false");}for(const id of [CASTLE_SYMBOL,CASTLE_LABELS,ZONE_FILL,ZONE_LINE])setLayerVisibility(id,castleMode);for(const id of ["spots-symbol","spots-labels","checkin-zone-fill","checkin-zone-line"])setLayerVisibility(id,!castleMode);const toolsToggle=document.getElementById("btnMapToolsToggle"),tools=document.getElementById("mapToolsPanel");if(toolsToggle)toolsToggle.hidden=castleMode;if(castleMode&&tools){tools.hidden=true;tools.setAttribute("aria-hidden","true");}document.querySelector(".map-shell")?.classList.toggle("castle-map-mode-v62",castleMode);if(onsenPanel)onsenPanel.hidden=castleMode;if(castlePanel)castlePanel.hidden=!castleMode;if(castleMode){if(selectedCastleId){renderCastleZone(selectedCastleId);updatePanel();}else clearCastleZone();}else{clearCastleZone();try{if(typeof selectedSpot!=="undefined"&&selectedSpot&&typeof renderCheckinZones==="function")renderCheckinZones(selectedSpot);if(typeof updateDistanceAndButton==="function")updateDistanceAndButton();}catch{}}requestAnimationFrame(()=>targetMap?.resize?.());window.dispatchEvent(new CustomEvent("onsen-map-domain-changed",{detail:{build:BUILD,mode}}));}
  function showCastle(castleId){window.OnsenAppShell?.show?.("map");setMode("castle");setTimeout(()=>selectCastle(castleId,{fly:true}),60);}

  function decorateCastleRows(){const root=document.getElementById("castleListRoot");if(!root)return false;for(const row of root.querySelectorAll(".castle-row")){if(row.querySelector("[data-castle-map-v62]"))continue;const node=row.querySelector("[data-castle-id]"),castleId=node?.dataset.castleId;if(!castleId||!zoneFor(castleId))continue;const actions=row.querySelector(".castle-actions");if(!actions)continue;const button=document.createElement("button");button.type="button";button.className="castle-map-link-v62";button.dataset.castleMapV62=castleId;button.textContent="地図";actions.insertBefore(button,actions.firstChild);}if(!root.dataset.castleMapBoundV62){root.dataset.castleMapBoundV62="1";root.addEventListener("click",(event)=>{const button=event.target instanceof Element?event.target.closest("[data-castle-map-v62]"):null;if(!button)return;event.preventDefault();event.stopPropagation();showCastle(button.dataset.castleMapV62);},true);}if(!mapLinksObserver){mapLinksObserver=new MutationObserver(()=>requestAnimationFrame(decorateCastleRows));mapLinksObserver.observe(root,{childList:true,subtree:true});}return true;}

  async function install(){if(installed)return;installed=true;for(let i=0;i<400;i+=1){if(getMap()&&window.OnsenCastleDomain&&window.OnsenCastleVisits)break;await new Promise((resolve)=>setTimeout(resolve,25));}loadZonesFromDomain();ensureModeSwitch();ensureCastlePanel();const targetMap=getMap();if(targetMap?.isStyleLoaded?.())installLayers();else targetMap?.once?.("load",installLayers);window.addEventListener("onsen-castle-visit-changed",()=>{refreshSource();updatePanel();requestAnimationFrame(decorateCastleRows);});window.addEventListener("onsen-character-state-changed",updatePanel);window.addEventListener("onsen-character-runtime-ready",updatePanel);window.addEventListener("onsen-app-tab-changed",(event)=>{if(event.detail?.tab==="map")setTimeout(applyMode,20);if(event.detail?.tab==="collection")setTimeout(decorateCastleRows,80);});window.addEventListener("pageshow",()=>{refreshSource();updatePanel();});document.getElementById("btnLocate")?.addEventListener("click",()=>{if(mode==="castle")setTimeout(()=>resolveCurrentPosition(false),80);});let attempts=0;const timer=setInterval(()=>{decorateCastleRows();attempts+=1;if(attempts>=30||mapLinksObserver)clearInterval(timer);},300);window.OnsenCastleMap={build:BUILD,setMode,getMode:()=>mode,showCastle,selectCastle,refresh:()=>{refreshSource();updatePanel();},resolveCurrentPosition,zones:()=>zoneData,selectedCastleId:()=>selectedCastleId};applyMode();window.dispatchEvent(new CustomEvent("onsen-castle-map-ready",{detail:{build:BUILD,entries:zoneData.entries.length}}));}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>install().catch((error)=>console.warn("castle map v68 init failed",error)),{once:true});else install().catch((error)=>console.warn("castle map v68 init failed",error));
})();