(() => {
  const BUILD = "v73";
  const SOURCE = "scenic-v71";
  const SYMBOL = "scenic-v71-symbol";
  const LABELS = "scenic-v71-labels";
  const ZONE_SOURCE = "scenic-v71-zone";
  const ZONE_FILL = "scenic-v71-zone-fill";
  const ZONE_LINE = "scenic-v71-zone-line";
  const LOCATION_MAX_AGE_MS = 2 * 60 * 1000;

  let installed = false;
  let controllerActive = false;
  let selectedId = null;
  let position = null;
  let mapBound = false;

  const sleep=(ms)=>new Promise((resolve)=>setTimeout(resolve,ms));
  function getMap(){try{return typeof map!=="undefined"?map:null;}catch{return null;}}
  function runtime(){return window.OnsenScenicRuntime||null;}
  function esc(value){return String(value??"").replace(/[&<>'\"]/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
  function shortName(entry){return String(entry?.name||"").split(/\r?\n/)[0].trim();}
  function formatDistance(m){const n=Number(m);if(!Number.isFinite(n))return "—";return n<1000?`${Math.round(n)}m`:`${(n/1000).toFixed(n<10000?1:0)}km`;}
  function haversineM(lat1,lng1,lat2,lng2){const R=6371000,rad=(v)=>v*Math.PI/180,dLat=rad(lat2-lat1),dLng=rad(lng2-lng1),a=Math.sin(dLat/2)**2+Math.cos(rad(lat1))*Math.cos(rad(lat2))*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
  function circlePolygon(lat,lng,radiusM,steps=64){const R=6371000,latRad=lat*Math.PI/180,latDelta=radiusM/R,lngDelta=radiusM/(R*Math.max(.15,Math.cos(latRad))),coords=[];for(let i=0;i<=steps;i++){const a=i/steps*Math.PI*2;coords.push([lng+lngDelta*Math.cos(a)*180/Math.PI,lat+latDelta*Math.sin(a)*180/Math.PI]);}return {type:"Polygon",coordinates:[coords]};}

  function createIcon(fill,border,special=false){const size=96,c=document.createElement("canvas");c.width=size;c.height=size;const x=c.getContext("2d");x.clearRect(0,0,size,size);x.beginPath();x.arc(48,48,38,0,Math.PI*2);x.fillStyle=fill;x.fill();x.lineWidth=7;x.strokeStyle=border;x.stroke();x.strokeStyle="#fff8e9";x.fillStyle="#fff8e9";x.lineWidth=5;x.lineJoin="round";x.beginPath();x.moveTo(20,62);x.lineTo(37,42);x.lineTo(47,52);x.lineTo(60,34);x.lineTo(77,62);x.stroke();x.beginPath();x.moveTo(21,66);x.quadraticCurveTo(48,58,75,66);x.stroke();if(special){x.fillStyle="#fff1a8";x.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?5:10,px=73+Math.cos(a)*r,py=23+Math.sin(a)*r;i===0?x.moveTo(px,py):x.lineTo(px,py);}x.closePath();x.fill();}return x.getImageData(0,0,size,size);}
  function ensureIcons(m){const icons={"scenic-v71-unvisited":createIcon("#55486e","#332a46"),"scenic-v71-special":createIcon("#684965","#3f2c3d",true),"scenic-v71-visited":createIcon("#8d7134","#59451f"),"scenic-v71-gps":createIcon("#43765a","#28503a")};for(const [id,img] of Object.entries(icons)){try{if(!m.hasImage(id))m.addImage(id,img,{pixelRatio:2});}catch{}}}
  function buildGeoJson(){const rt=runtime();if(!rt)return {type:"FeatureCollection",features:[]};const state=rt.loadState?.()||{visited:{}};const features=[];for(const entry of rt.entries?.()||[]){const refs=rt.referenceZones?.(entry)||[];if(!refs.length)continue;const p=refs[0],record=state.visited?.[entry.id]||null;features.push({type:"Feature",properties:{id:entry.id,name:shortName(entry),special:entry.specialScenic===true,visited:!!record,gps:record?.verificationType==="gps_scenic",gpsReady:!!rt.isGpsReady?.(entry),prefecture:(entry.prefectures||[]).join("・")},geometry:{type:"Point",coordinates:[Number(p.lng),Number(p.lat)]}});}return {type:"FeatureCollection",features};}
  function refreshSource(){getMap()?.getSource(SOURCE)?.setData?.(buildGeoJson());}
  function clearZone(){getMap()?.getSource(ZONE_SOURCE)?.setData?.({type:"FeatureCollection",features:[]});}
  function renderZone(id){const rt=runtime(),source=getMap()?.getSource(ZONE_SOURCE);if(!rt||!source)return false;const zones=rt.auditedZones?.(id)||[];source.setData({type:"FeatureCollection",features:zones.map((zone)=>({type:"Feature",properties:{id,zoneId:zone.id,radiusM:zone.radiusM,label:zone.label||""},geometry:circlePolygon(Number(zone.lat),Number(zone.lng),Math.max(500,Number(zone.radiusM)||750))}))});return true;}

  function ensureLayers(){const m=getMap(),rt=runtime();if(!m||!rt||!m.isStyleLoaded?.())return false;ensureIcons(m);try{if(!m.getSource(SOURCE))m.addSource(SOURCE,{type:"geojson",data:buildGeoJson()});else refreshSource();}catch{return false;}try{if(!m.getLayer(SYMBOL))m.addLayer({id:SYMBOL,type:"symbol",source:SOURCE,layout:{visibility:"none","icon-image":["case",["==",["get","gps"],true],"scenic-v71-gps",["==",["get","visited"],true],"scenic-v71-visited",["==",["get","special"],true],"scenic-v71-special","scenic-v71-unvisited"],"icon-size":["interpolate",["linear"],["zoom"],4.6,.32,8,.48,12,.66],"icon-allow-overlap":true,"icon-ignore-placement":true}});}catch{}try{if(!m.getLayer(LABELS))m.addLayer({id:LABELS,type:"symbol",source:SOURCE,minzoom:7.2,layout:{visibility:"none","text-field":["get","name"],"text-size":["interpolate",["linear"],["zoom"],7.2,10,12,13],"text-offset":[0,1.8],"text-anchor":"top","text-optional":true},paint:{"text-color":"#55485d","text-halo-color":"#fffaf0","text-halo-width":1.5}});}catch{}try{if(!m.getSource(ZONE_SOURCE))m.addSource(ZONE_SOURCE,{type:"geojson",data:{type:"FeatureCollection",features:[]}});}catch{}try{if(!m.getLayer(ZONE_FILL))m.addLayer({id:ZONE_FILL,type:"fill",source:ZONE_SOURCE,layout:{visibility:"none"},paint:{"fill-color":"#7d5a92","fill-opacity":.13}});}catch{}try{if(!m.getLayer(ZONE_LINE))m.addLayer({id:ZONE_LINE,type:"line",source:ZONE_SOURCE,layout:{visibility:"none"},paint:{"line-color":"#75528b","line-width":2,"line-opacity":.88}});}catch{}if(selectedId)renderZone(selectedId);else clearZone();bindMapInteractions();window.dispatchEvent(new CustomEvent("onsen-scenic-map-layers-ready",{detail:{build:BUILD}}));return true;}

  function chooseFeature(event){const m=getMap();if(!m)return null;const layers=[SYMBOL,LABELS].filter((id)=>m.getLayer(id));if(!layers.length)return null;let features=[];try{features=m.queryRenderedFeatures(event.point,{layers});}catch{}if(!features.length)return null;const unique=new Map();for(const f of features){const id=String(f?.properties?.id||"");if(id&&!unique.has(id))unique.set(id,f);}if(unique.size<=1)return [...unique.values()][0]||null;const click=event.lngLat;let best=null,bestD=Infinity;for(const f of unique.values()){const id=String(f.properties.id),refs=runtime()?.referenceZones?.(id)||[];const p=refs[0];if(!p)continue;const d=haversineM(click.lat,click.lng,Number(p.lat),Number(p.lng));if(d<bestD){best=f;bestD=d;}}return best||[...unique.values()][0]||null;}
  function bindMapInteractions(){const m=getMap();if(!m||mapBound)return;mapBound=true;m.on("click",(event)=>{if(!controllerActive)return;const feature=chooseFeature(event);const id=feature?.properties?.id;if(id)selectScenic(id,{fly:false});});m.on("mousemove",(event)=>{if(!controllerActive)return;const layers=[SYMBOL,LABELS].filter((id)=>m.getLayer(id));if(!layers.length)return;let hit=[];try{hit=m.queryRenderedFeatures(event.point,{layers});}catch{}m.getCanvas().style.cursor=hit.length?"pointer":"";});m.on("style.load",()=>{setTimeout(()=>{ensureLayers();window.OnsenMapDomainV73?.apply?.();},0);});}

  function ensurePanel(){const main=document.querySelector(".main"),onsenPanel=main?.querySelector(":scope > .panel:not(.castle-map-panel-v62):not(.scenic-map-panel-v71)");if(!main||!onsenPanel)return null;let panel=document.getElementById("scenicMapPanelV71");if(panel)return panel;panel=document.createElement("section");panel.id="scenicMapPanelV71";panel.className="panel scenic-map-panel-v71";panel.hidden=true;panel.innerHTML=`<div class="scenic-map-empty-v71" id="scenicMapEmptyV71"><span>NATIONAL PLACES OF SCENIC BEAUTY</span><h2>名勝を選択</h2><p>地図の名勝ピンをタップしてください。</p></div><div id="scenicMapDetailV71" hidden><div class="scenic-map-title-v71"><div><span id="scenicMapKindV71">名勝</span><h2 id="scenicMapNameV71">名勝</h2><p id="scenicMapPlaceV71"></p></div><b id="scenicMapStatusV71">未訪問</b></div><div class="scenic-map-metrics-v71"><div><span>距離</span><b id="scenicMapDistanceV71">現在地未取得</b></div><div><span>GPS精度</span><b id="scenicMapAccuracyV71">—</b></div><div><span>GPS判定</span><b id="scenicMapRadiusV71">—</b></div></div><div class="scenic-map-actions-v71"><button id="scenicMapLocateV71" type="button" class="secondary">現在地を確認</button><button id="scenicMapCheckinV71" type="button" disabled>名勝チェックイン</button></div><div id="scenicMapMessageV71" class="scenic-map-message-v71">GPS判定範囲を確認できます。</div><details class="details"><summary>GPS判定について</summary><p class="note">判定半径は500m未満にしません。広域・複合名勝は複数zoneで判定します。</p></details></div>`;const castle=document.getElementById("castleMapPanelV62");(castle||onsenPanel).insertAdjacentElement("afterend",panel);panel.querySelector("#scenicMapLocateV71")?.addEventListener("click",()=>resolvePosition(true));panel.querySelector("#scenicMapCheckinV71")?.addEventListener("click",performCheckin);return panel;}

  function selectedReferenceDistance(){const refs=runtime()?.referenceZones?.(selectedId)||[];if(!position||!refs.length)return null;return Math.min(...refs.map((z)=>haversineM(position.lat,position.lng,Number(z.lat),Number(z.lng))));}
  function selectedEvaluation(){return selectedId&&position?runtime()?.evaluatePosition?.(position,selectedId)||null:null;}
  function updatePanel(){const rt=runtime(),panel=ensurePanel(),entry=rt?.get?.(selectedId),empty=document.getElementById("scenicMapEmptyV71"),detail=document.getElementById("scenicMapDetailV71");if(!panel||!empty||!detail)return;if(!entry){empty.hidden=false;detail.hidden=true;return;}empty.hidden=true;detail.hidden=false;const record=rt.loadState().visited?.[entry.id]||null,gpsReady=rt.isGpsReady(entry),refs=rt.referenceZones(entry),zones=rt.auditedZones(entry),evaluation=selectedEvaluation(),refDistance=selectedReferenceDistance(),fresh=position&&Date.now()-Number(position.sampledAt||0)<=LOCATION_MAX_AGE_MS;document.getElementById("scenicMapKindV71").textContent=entry.specialScenic?"特別名勝":"国指定名勝";document.getElementById("scenicMapNameV71").textContent=shortName(entry);document.getElementById("scenicMapPlaceV71").textContent=`${(entry.prefectures||[]).join("・")}${entry.location?` ・ ${entry.location}`:""}`;const status=document.getElementById("scenicMapStatusV71");status.textContent=record?.verificationType==="gps_scenic"?"GPS確認済":record?"訪問登録済":"未訪問";status.className=record?.verificationType==="gps_scenic"?"strict":record?"visited":"";document.getElementById("scenicMapDistanceV71").textContent=refDistance==null?"現在地未取得":formatDistance(refDistance);document.getElementById("scenicMapAccuracyV71").textContent=fresh&&Number.isFinite(Number(position?.accuracyM))?`${Math.round(Number(position.accuracyM))}m`:"—";document.getElementById("scenicMapRadiusV71").textContent=gpsReady&&zones.length?(zones.length>1?`${zones.length}地点 / ${formatDistance(zones[0].radiusM)}`:formatDistance(zones[0].radiusM)):refs.length?"参照点のみ":"座標なし";const check=document.getElementById("scenicMapCheckinV71"),message=document.getElementById("scenicMapMessageV71"),gpsDone=record?.verificationType==="gps_scenic";check.disabled=gpsDone||!evaluation?.ok;check.textContent=gpsDone?"GPS確認済":"名勝チェックイン";if(gpsDone)message.innerHTML="<strong>GPS確認済みです。</strong>";else if(!position)message.textContent="「現在地を確認」でGPSを取得してください。";else if(evaluation?.reason==="accuracy_too_low")message.textContent=`GPS精度が不足しています（現在約${Math.round(position.accuracyM)}m / 許容500m）。`;else if(evaluation?.reason==="out_of_range")message.textContent=`判定範囲外です。参照点まで約${formatDistance(refDistance)}です。`;else if(evaluation?.reason==="position_stale")message.textContent="位置情報が古いため再取得してください。";else if(evaluation?.ok)message.innerHTML=`<strong>チェックイン可能です。</strong> ${esc(evaluation.best?.zone?.label||"")}`;else message.textContent="現在地を確認してください。";}

  function resolvePosition(center=false){const message=document.getElementById("scenicMapMessageV71");if(!navigator.geolocation){if(message)message.textContent="この端末は位置情報取得に対応していません。";return Promise.resolve(null);}if(message)message.textContent="現在地を高精度で確認しています…";return new Promise((resolve)=>navigator.geolocation.getCurrentPosition((p)=>{position={lat:Number(p.coords.latitude),lng:Number(p.coords.longitude),accuracyM:Number(p.coords.accuracy||0),sampledAt:Number(p.timestamp||Date.now())};if(center)getMap()?.flyTo?.({center:[position.lng,position.lat],zoom:Math.max(12,getMap()?.getZoom?.()||12)});updatePanel();resolve(position);},(error)=>{console.warn("scenic geolocation failed",error);position=null;if(message)message.textContent="現在地を取得できませんでした。";updatePanel();resolve(null);},{enableHighAccuracy:true,timeout:12000,maximumAge:3000}));}
  function performCheckin(){if(!selectedId||!position)return;const result=runtime()?.registerGpsVisit?.(selectedId,position);if(!result?.ok){updatePanel();return;}refreshSource();updatePanel();try{navigator.vibrate?.([70,40,120]);}catch{}}
  function selectScenic(id,options={}){const entry=runtime()?.get?.(id),refs=runtime()?.referenceZones?.(id)||[];if(!entry)return false;selectedId=entry.id;renderZone(entry.id);updatePanel();window.OnsenMapDomainV73?.apply?.();if(options.fly!==false&&refs.length)getMap()?.flyTo?.({center:[Number(refs[0].lng),Number(refs[0].lat)],zoom:Math.max(11,getMap()?.getZoom?.()||11)});return true;}
  function setControllerActive(active){controllerActive=!!active;if(!controllerActive)getMap()&&(getMap().getCanvas().style.cursor="");if(controllerActive&&selectedId)renderZone(selectedId);return controllerActive;}

  async function install(){if(installed)return;installed=true;for(let i=0;i<300;i++){if(runtime()&&getMap())break;await sleep(40);}if(!runtime()||!getMap()){console.warn("scenic map v73 prerequisites not ready");return;}ensurePanel();ensureLayers();bindMapInteractions();window.addEventListener("onsen-scenic-visit-changed",()=>{refreshSource();updatePanel();});window.addEventListener("pageshow",()=>{ensureLayers();refreshSource();updatePanel();});window.OnsenScenicMapV71={build:BUILD,ensureLayers,setControllerActive,selectedId:()=>selectedId,select:selectScenic,resolvePosition,refresh:()=>{ensureLayers();refreshSource();updatePanel();},active:()=>controllerActive,show:(id)=>window.OnsenMapDomainV73?.open?.("scenic",id,{source:"scenic-api"}),showMode:()=>window.OnsenMapDomainV73?.setMode?.("scenic",{source:"scenic-api"})};window.dispatchEvent(new CustomEvent("onsen-scenic-map-ready",{detail:{build:BUILD}}));}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>install().catch((e)=>console.warn("scenic map v73 init failed",e)),{once:true});else install().catch((e)=>console.warn("scenic map v73 init failed",e));
})();